In [12]:
import os
import pandas as pd

In [13]:
path = './all_games.csv'

In [14]:
df_2022 = pd.read_csv('./csv/gl2022.csv')

In [15]:
# Get the column with data out of there, add temporary ordered numbers for the column names
# This allows for me to select the columns I want, and add names to those few I want later.
df_2022.loc[-1] = df_2022.columns.values
df_2022.sort_index(inplace = True)
df_2022.reset_index(drop=True, inplace=True)
df_2022.set_axis([str(num) for num in range(len(df_2022.columns))], axis = "columns", inplace=True)

In [25]:
# Remove column 160. According to retrosheet, this column shows if their system has all the information possible for that game. Since all the games for 2022 have all data, we can confidently remove this column.
df_2022.drop(columns = '160')

,0,1,2,3,4,5,6,7,8,9,...,150,151,152,153,154,155,156,157,158,159
0,20220407,0,Thu,SDN,NL,1,ARI,NL.1,1.1,2,...,beers001.1,Seth Beer.1,10.1,ellid002,Drew Ellis,5.3,perdg001,Gerardo Perdomo,6.4,Unnamed: 159
1,20220407,0,Thu,CIN,NL,1,ATL,NL,1,6,...,darnt001,Travis d'Arnaud,2,dicka001,Alex Dickerson,10,swand001,Dansby Swanson,6,NaN
2,20220407,0,Thu,MIL,NL,1,CHN,NL,1,4,...,heywj001,Jason Heyward,8,wisdp001,Patrick Wisdom,5,hoern001,Nico Hoerner,6,NaN
3,20220407,0,Thu,PIT,NL,1,SLN,NL,1,0,...,moliy001,Yadier Molina,2,badeh001,Harrison Bader,8,edmat001,Tommy Edman,4,NaN
4,20220407,0,Thu,NYN,NL,1,WAS,NL,1,5,...,franm004,Maikel Franco,5,escoa003,Alcides Escobar,6,roblv001,Victor Robles,8,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2425,20221005,0,Wed,KCA,AL,162,CLE,AL,162,2,...,brenw002,Will Brennan,7,maill001,Luke Maile,2,stram002,Myles Straw,8,NaN
2426,20221005,0,Wed,PHI,NL,162,HOU,AL,162,2,...,meyej002,Jake Meyers,8,dubom001,Mauricio Dubon,6,maldm001,Martin Maldonado,2,NaN
2427,20221005,0,Wed,ANA,AL,162,OAK,AL,162,2,...,capec001,Conner Capel,9,garcd004,Dermis Garcia,3,allen002,Nick Allen,6,NaN
2428,20221005,0,Wed,DET,AL,162,SEA,AL,162,4,...,toroa001,Abraham Toro,5,casac001,Curt Casali,2,crawj002,J.P. Crawford,6,NaN
2429,20221005,0,Wed,NYA,AL,162,TEX,AL,162,2,...,culbc001,Charlie Culberson,7,tavel001,Leody Taveras,8,thomb003,Bubba Thompson,9,NaN